### ISSUE TITLE
The testing results are inconsistent when I use 'torch.quantization.convert' or not

### ISSUE THREAD

**Issue by Derteanoo** [clovaai/StatAssist-GradBoost#4]
Hello, may I ask you some questions?

When I do 
`   
model.fuse_model()
model.qconfig =  torch.quantization.get_default_qat_qconfig('qnnpack')
torch.quantization.prepare_qat(model, inplace=True)
model.load_state_dict(torch.load(Max_name, "cpu")) 
model.eval().to('cpu')
test(model)
`
and
` 
model.fuse_model()
model.qconfig =  torch.quantization.get_default_qat_qconfig('qnnpack')
torch.quantization.prepare_qat(model, inplace=True)
model.load_state_dict(torch.load(Max_name, "cpu")) 
torch.quantization.convert(model.eval(),inplace = True)
test(model)
`
the testing results are inconsistent. Is this phenomenon reasonable?
‘torch.quantization.convert’ is used to merge 'conv bn relu' and remove fake quantize nodes, why does it affect the result value?

**Comment by tgisaturday** [comment]
Your first command runs model in FLOAT32 with fake-quantized models. Second one runs model in INT8 quantized setting. Since FLOAT32 -> INT8 makes weight values more discrete (compressed), testing results also changes. The latency between two might be different also. 

Thank you for using our code. Please feel free to ask if you have any questions :)
